gpt_config:
  vocab_size: 4
  seq_len: 64
  embed_dim: 16
  ff_dim: 128
  num_heads: 4
  num_layers: 4
  drop_rate: 0.0
optimizer_config:
  lr: 0.0003
  n_steps: 100
  warmup_steps: 10
  weight_decay: 0.0
train_config:
  batch_size: 32
  loss_weighting: "unweighted"
  n_steps: 100
  seed: 42
  save_freq: 20
  val_freq: 10
