train_dataset_path: "text_dataset/train_wikipedia.npy"
val_dataset_path: "text_dataset/val_wikipedia.npy"
batch_size: 64
gen_batch_size: 64
grad_batch_size: 1
n_steps: 100000
seed: 42
save_freq: 2000
save_intermediate: false
val_freq: 2000
n_val_steps: 10
log_freq: 500
logging: "wandb"