train_dataset_path: "text_dataset/train_wikipedia.npy"
val_dataset_path: "text_dataset/val_wikipedia.npy"
batch_size: 128
n_steps: 200000
seed: 42
save_freq: 2000
save_intermediate: false
val_freq: 2000
n_val_steps: 100
log_freq: 1000
logging: "wandb"