cfg_name: "cfg3b"
train_dataset_path: "cfg_dataset/cfg3b_100000_train.txt"
val_dataset_path: "cfg_dataset/cfg3b_100000_val.txt"
batch_size: 64
gen_batch_size: 64
n_steps: 100000
seed: 42
save_freq: 5000
save_intermediate: false
val_freq: 2000
n_val_steps: 10
log_freq: 500
logging: "wandb"