train_dataset_path: "text_dataset/train_wikipedia.npy"
val_dataset_path: "text_dataset/val_wikipedia.npy"
batch_size: 4
gen_batch_size: 4
n_steps: 10000
seed: 42
save_freq: 1000
save_intermediate: false
val_freq: 100
n_val_steps: 10
log_freq: 100
logging: "stdout"