cfg_name: "simple4"
dataset_path: "cfg_dataset/simple4_100000_train.txt"
batch_size: 4
gen_batch_size: 4
loss_weighting: "negexp_relpos"
n_steps: 10000
seed: 42
save_freq: 1000
save_intermediate: false
val_freq: 100
n_val_steps: 10
log_freq: 100
logging: "stdout"